name: Scrape data

env:
  CI: true

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */12 * * *'

jobs:
  scrape:
    name: Scrape data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch
        run: git fetch --no-tags --prune --depth=1 origin main

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://npm.pkg.github.com'

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Scrape data
        run: yarn run start --if-present

      - name: Push data
        uses: EndBug/add-and-commit@v7
        with:
          author_name: my-slab
          author_email: mitch.stewart@hey.com
          message: 'chore: update data'
